config/routes.rb
Rails.application.routes.draw do
  resources :catch_rates

  resources :dbless_catch_rates

  resources :articles do
    resources :comments
  end

  resources :questions

  resources :games

  get '/multiplechoice' => 'pages#multiplechoice'
  get '/quiz_lite' => 'pages#quiz_lite'
  get '/christmas' => 'pages#christmas'
  get '/questions/test_partial' => 'questions#test'

  root 'welcome#index'
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_and_belongs_to_many :sources
	belongs_to :type
	validates :body, presence: true
    validates :answer, presence: true
    validates :type, presence: true
    self.inheritance_column = nil
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	http_basic_authenticate_with name: "noob", password: "king"

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
 		@question.type_id = params[:question][:type_id]
 		@question.source_ids = params[:question][:source_ids]

  		if @question.save
    		redirect_to @question
  		else
    		render 'new'
		end
  end

  def show
  		@question = Question.find(params[:id])
	end

	def index
		@questions = Question.all
	end

	def edit
  		@question = Question.find(params[:id])
	end

	def update
  		@question = Question.find(params[:id])
 		@question.sources.delete_all
  		if @question.update(question_params)
    		redirect_to @question
  		else
    		render 'edit'
  		end
  	end

  	def destroy
  		@question = Question.find(params[:id])
  		@question.destroy
  		redirect_to questions_path
	end

	private
		def question_params
  		params.require(:question).permit(:body, :answer, :option1, :option2, :option3, :option4, :option5, :type_id, {:source_ids => []})
		end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container class">
    <div class="eight columns offset-by-four">
      <p>
        <h5> Question </h5>
        <%= f.text_area :body, :class => "form_text" %>
      </p>
     
      <p>
        <h5> Answer </h5>
        <%= f.text_field :answer, :size => 800 %>
      </p>

      <p>
        <h5> Question Type </h5>
        <%= f.collection_select :type_id, Type.all, :id, :name %> 
      </p>

      <p>
        <% Source.all.each do |source| %>
          <%= check_box_tag "question[source_ids][]", source.id, @question.sources.include?(source) %>
          <%= source.name %>&nbsp;&nbsp;
        <% end %>
      </p>

      <p>
        <h5> A </h5>
        <%= f.text_field :option1, :class => "form_text" %>
      </p>

      <p>
        <h5> B </h5>
        <%= f.text_field :option2, :class => "form_text" %>
      </p>

      <p>
        <h5> C </h5> 
        <%= f.text_field :option3, :class => "form_text" %>
      </p>

      <p>
        <h5> D </h5>
        <%= f.text_field :option4, :class => "form_text" %>
      </p>

      <p>
        <h5> E </h5>
        <%= f.text_field :option5, :class => "form_text" %>
      </p>


     
      <p>
        <%= f.submit %>
      </p>
    </div>
  </div>
<% end %>

app/views/questions/_show.html.erb
<div class="container brown menu_margin">
	<div class="menu_margin">
		<div class="center">
			<h2>Question ID: <%= @question.id %></h2>
		</div>
		 
		<p>
			Body: <%= @question.body %>
		</p>

		<p>
			Answer: <%=@question.answer %> <br/>
			Option 1: <%=@question.option1 %> <br/>
			Option 2: <%=@question.option2 %> <br/>
			Option 3: <%=@question.option3 %> <br/>
			Option 4: <%=@question.option4 %> <br/>
			Option 5: <%=@question.option5 %> <br/>
			Type: <%=@question.type.name %>
		</p>

		<p>
			Sources:
			<% @question.sources.each do |source| %>
				<%= source.name %> /
			<% end %>
		</p>

		<hr>

	</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>
  <div class="container">
  <%= link_to 'New Question', new_question_path, :class=>"button one column" %>
</div>
<div class="container brown">
  <% @questions.each do |question| %>
    <div class="sixteen columns">
      <div class="three columns">
        Question: <%= question.body %>
      </div>
      <div class="nine columns">
        Answer: <%= question.answer %>
      </div>
      <div class="one column">
        <%= link_to 'Show', question_path(question), :class=>"button" %>
      </div>
      <div class="one column">
        <%= link_to 'Edit', edit_question_path(question), :class=>"button" %>
      </div>
      <div class="one column">
        <%= link_to 'Destroy', question_path(question), method: :delete, data: { confirm: 'Are you sure?' }, :class=>"button" %>
      </div>
    </div>
    <div class="sixteen columns">
      <div class="three columns">
        Option 1: <%= question.option1 %>
      </div>
      <div class="three columns">
        Option 2: <%= question.option2 %>
      </div>
      <div class="three columns">
        Option 3: <%= question.option3 %>
      </div>
      <div class="three columns">
        Option 4: <%= question.option4 %>
      </div>
      <div class="three columns">
        Option 5: <%= question.option5 %>
      </div>
    </div>
    <hr/>
    &nbsp;
  <% end %>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="container brown menu_margin">
	<div class="menu_margin">
		<div class="center">
			<h2>Question ID: <%= @question.id %></h2>
		</div>
		 
		<p>
			Body: <%= @question.body %>
		</p>

		<p>
			Answer: <%=@question.answer %> <br/>
			Option 1: <%=@question.option1 %> <br/>
			Option 2: <%=@question.option2 %> <br/>
			Option 3: <%=@question.option3 %> <br/>
			Option 4: <%=@question.option4 %> <br/>
			Option 5: <%=@question.option5 %> <br/>
			Type: <%=@question.type.name %>
		</p>

		<p>
			Sources:
			<% @question.sources.each do |source| %>
				<%= source.name %> /
			<% end %>
		</p>

		<hr>
		<%= link_to 'Edit', edit_question_path(@question), :class=>"button" %>

	</div>
</div>